version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./log.json:/app/log.json
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
